# Generated by Django 5.0 on 2023-12-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phoneNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
